# Generated by Django 2.2.15 on 2020-09-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('datePub', models.DateTimeField(auto_now_add=True)),
                ('lastMod', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('topic', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='Posts.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('commentText', models.TextField()),
                ('post', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='Posts.Post')),
            ],
        ),
    ]
